"""Initial StoneFixer migration with all models

Revision ID: 4e5d5a9d1060
Revises: 
Create Date: 2025-09-17 17:59:12.498487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e5d5a9d1060'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tech_asset',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('serial_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('supplier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('invoice', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('warranty_expiry', sa.DateTime(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_assigned', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('specifications', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_index(op.f('ix_tech_asset_asset_tag'), 'tech_asset', ['asset_tag'], unique=True)
    op.create_index(op.f('ix_tech_asset_name'), 'tech_asset', ['name'], unique=False)
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('asset_assignments',
    sa.Column('tech_asset_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_date', sa.DateTime(), nullable=False),
    sa.Column('expected_return_date', sa.DateTime(), nullable=True),
    sa.Column('actual_return_date', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assignment_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location_of_use', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('condition_at_assignment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('condition_at_return', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assignment_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('return_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tech_asset_id'], ['tech_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_maintenances',
    sa.Column('tech_asset_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('estimated_duration_hours', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('procedures_performed', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parts_replaced', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tools_used', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('labor_cost', sa.Float(), nullable=True),
    sa.Column('parts_cost', sa.Float(), nullable=True),
    sa.Column('external_service_cost', sa.Float(), nullable=True),
    sa.Column('maintenance_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('warranty_work', sa.Boolean(), nullable=False),
    sa.Column('follow_up_required', sa.Boolean(), nullable=False),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attachments', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tech_asset_id'], ['tech_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role')
    )
    op.drop_table('test_connection')
    op.drop_table('prueba')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prueba',

    )
    op.create_table('test_connection',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_connection_pkey'))
    )
    op.drop_table('user_roles')
    op.drop_table('asset_maintenances')
    op.drop_table('asset_assignments')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tech_asset_name'), table_name='tech_asset')
    op.drop_index(op.f('ix_tech_asset_asset_tag'), table_name='tech_asset')
    op.drop_table('tech_asset')
    # ### end Alembic commands ###
