"""Agrego nuevos campos a modelos existentes

Revision ID: 56cbf2769390
Revises: 7e3674ff80d3
Create Date: 2026-06-15 19:07:45.481754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '56cbf2769390'
down_revision: Union[str, Sequence[str], None] = '7e3674ff80d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_assignments', sa.Column('humand_send_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('asset_assignments', sa.Column('humand_error_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('asset_assignments', sa.Column('humand_last_attempt_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_assignments', 'humand_last_attempt_at')
    op.drop_column('asset_assignments', 'humand_error_detail')
    op.drop_column('asset_assignments', 'humand_send_status')
    # ### end Alembic commands ###
