"""add_assignment_document_field

Revision ID: 7e3674ff80d3
Revises: 53a2c5f24583
Create Date: 2026-02-08 23:13:19.304854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7e3674ff80d3'
down_revision: Union[str, Sequence[str], None] = '53a2c5f24583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_assignments', sa.Column('accessories', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('asset_assignments', sa.Column('humand_document_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('asset_assignments', sa.Column('document_sent_to_humand', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('asset_assignments', sa.Column('document_sent_at', sa.DateTime(), nullable=True))
    op.add_column('asset_assignments', sa.Column('humand_folder_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('dni_encrypted', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('dni_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('personal_data_consent', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user', sa.Column('personal_data_consent_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_dni_hash'), 'user', ['dni_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_dni_hash'), table_name='user')
    op.drop_column('user', 'personal_data_consent_date')
    op.drop_column('user', 'personal_data_consent')
    op.drop_column('user', 'dni_hash')
    op.drop_column('user', 'dni_encrypted')
    op.drop_column('asset_assignments', 'humand_folder_id')
    op.drop_column('asset_assignments', 'document_sent_at')
    op.drop_column('asset_assignments', 'document_sent_to_humand')
    op.drop_column('asset_assignments', 'humand_document_name')
    op.drop_column('asset_assignments', 'accessories')
    # ### end Alembic commands ###
