"""add connector_type to tech_asset

Revision ID: 902c807c3f2f
Revises: 69191f691ae8
Create Date: 2026-08-22 20:38:14.240918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '902c807c3f2f'
down_revision: Union[str, Sequence[str], None] = '69191f691ae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tech_asset', sa.Column('connector_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tech_asset', 'connector_type')
    # ### end Alembic commands ###
