"""Initial migration with all existing models

Revision ID: 9f2ba848bd5f
Revises: 
Create Date: 2026-01-10 19:06:31.621508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9f2ba848bd5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_schedules',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('modified_by_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['modified_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_schedules_date'), 'shift_schedules', ['date'], unique=False)
    op.create_index(op.f('ix_shift_schedules_department'), 'shift_schedules', ['department'], unique=False)
    op.drop_index(op.f('ix_asset_documents_document_number'), table_name='asset_documents')
    op.drop_table('asset_documents')
    op.alter_column('tech_asset', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='Fecha de eliminación (soft-delete)',
               existing_nullable=True)
    op.alter_column('tech_asset', 'deleted_by_user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID del usuario que eliminó el activo',
               existing_nullable=True)
    op.drop_index(op.f('idx_tech_asset_deleted_at'), table_name='tech_asset')
    op.drop_constraint(op.f('fk_tech_asset_deleted_by_user'), 'tech_asset', type_='foreignkey')
    op.create_foreign_key(None, 'tech_asset', 'user', ['deleted_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tech_asset', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tech_asset_deleted_by_user'), 'tech_asset', 'user', ['deleted_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_tech_asset_deleted_at'), 'tech_asset', ['deleted_at'], unique=False)
    op.alter_column('tech_asset', 'deleted_by_user_id',
               existing_type=sa.INTEGER(),
               comment='ID del usuario que eliminó el activo',
               existing_nullable=True)
    op.alter_column('tech_asset', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de eliminación (soft-delete)',
               existing_nullable=True)
    op.create_table('asset_documents',
    sa.Column('tech_asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('document_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('document_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('generated_by_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('employee_dni', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('asset_description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('asset_condition', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('accessories_included', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('qr_code_data', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('document_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('signed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['asset_assignments.id'], name=op.f('asset_documents_assignment_id_fkey')),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['user.id'], name=op.f('asset_documents_generated_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['tech_asset_id'], ['tech_asset.id'], name=op.f('asset_documents_tech_asset_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('asset_documents_pkey'))
    )
    op.create_index(op.f('ix_asset_documents_document_number'), 'asset_documents', ['document_number'], unique=True)
    op.drop_index(op.f('ix_shift_schedules_department'), table_name='shift_schedules')
    op.drop_index(op.f('ix_shift_schedules_date'), table_name='shift_schedules')
    op.drop_table('shift_schedules')
    # ### end Alembic commands ###
