"""crea tablas inventario_snapshot e integracion_ejecucion

Revision ID: bb561f0f9c3f
Revises: 91792e69a88d
Create Date: 2026-09-23 23:58:43.956733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bb561f0f9c3f'
down_revision: Union[str, Sequence[str], None] = '91792e69a88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integracion_ejecucion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proceso', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('fecha_datos', sa.Date(), nullable=True),
    sa.Column('iniciado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalizado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('tipo_error', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('mensaje', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('filas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integracion_ejecucion_proceso'), 'integracion_ejecucion', ['proceso'], unique=False)
    op.create_table('inventario_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('deposito_id', sa.Integer(), nullable=False),
    sa.Column('deposito', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('rubro', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('familia', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('unidades', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('importe_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('importe_ars', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha', 'deposito_id', 'rubro', 'familia', name='uq_inventario_snapshot_clave')
    )
    op.create_index(op.f('ix_inventario_snapshot_fecha'), 'inventario_snapshot', ['fecha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventario_snapshot_fecha'), table_name='inventario_snapshot')
    op.drop_table('inventario_snapshot')
    op.drop_index(op.f('ix_integracion_ejecucion_proceso'), table_name='integracion_ejecucion')
    op.drop_table('integracion_ejecucion')
    # ### end Alembic commands ###
