"""add role_id fk to user_roles for rbac transition

Revision ID: bbf10ee24857
Revises: 5627ccdcd258
Create Date: 2026-09-21 23:27:06.376968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbf10ee24857'
down_revision: Union[str, Sequence[str], None] = '5627ccdcd258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_roles', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_column('user_roles', 'role_id')
    